#import "./transaction-fragment.gql"
mutation AddTransaction($userId: String, $description: String, $merchantId: String, $debit: Boolean, $credit: Boolean, $amount: Float, $date: String) {
    addTransaction(userId: $userId, description: $description, merchantId: $merchantId, debit: $debit, credit: $credit, amount: $amount, date: $date) {
       ...TransactionFragment 
    }
}