#import "./user-fragment.gql"

fragment TransactionFragment on Transaction {
  id
  user {
    ...UserFragment
  }
  merchant {
    id
    name
    category
    description
  }
  description
  debit
  credit
  amount
  date
}